heat_template_version: queens

parameters:
  public_key:
    type: string
    description: "the public key for access to the servers"

resources:
  keypairName:
    type: OS::Heat::RandomString
    properties:
      character_classes: [{"class": "hexdigits", "min": 1}]
      length: 32
      salt: constant
  keyPair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_attr: [keypairName, value] }
      public_key: { get_param: public_key }
      save_private_key: false

outputs:
  sshKey:
    description: "KeyPair ID"
    value: { get_resource: keyPair }